public class fromJSON{
    public cls_attributes attributes;
    public String Id;   
    public String Name; 
    public String Label;    
    public cls_ProfileId ProfileId;
    public boolean IsOwnedByProfile;
    public boolean IsCustom;
    public boolean PermissionsEmailSingle;
    public boolean PermissionsEmailMass;
    public boolean PermissionsEditTask;
    public boolean PermissionsEditEvent;
    public boolean PermissionsExportReport;
    public boolean PermissionsImportPersonal;
    public boolean PermissionsManageUsers;
    public boolean PermissionsEditPublicTemplates;
    public boolean PermissionsModifyAllData;
    public boolean PermissionsManageCases;
    public boolean PermissionsMassInlineEdit;
    public boolean PermissionsEditKnowledge;
    public boolean PermissionsManageKnowledge;
    public boolean PermissionsManageSolutions;
    public boolean PermissionsCustomizeApplication;
    public boolean PermissionsEditReadonlyFields;
    public boolean PermissionsRunReports;
    public boolean PermissionsViewSetup;
    public boolean PermissionsTransferAnyEntity;
    public boolean PermissionsNewReportBuilder;
    public boolean PermissionsActivateContract;
    public boolean PermissionsActivateOrder;
    public boolean PermissionsImportLeads;
    public boolean PermissionsManageLeads;
    public boolean PermissionsTransferAnyLead;
    public boolean PermissionsViewAllData;
    public boolean PermissionsEditPublicDocuments;
    public boolean PermissionsViewEncryptedData;
    public boolean PermissionsEditBrandTemplates;
    public boolean PermissionsEditHtmlTemplates;
    public boolean PermissionsChatterInternalUser;
    public boolean PermissionsManageEncryptionKeys;
    public boolean PermissionsDeleteActivatedContract;
    public boolean PermissionsChatterInviteExternalUsers;
    public boolean PermissionsSendSitRequests;
    public boolean PermissionsManageRemoteAccess;
    public boolean PermissionsCanUseNewDashboardBuilder;
    public boolean PermissionsManageCategories;
    public boolean PermissionsConvertLeads;
    public boolean PermissionsPasswordNeverExpires;
    public boolean PermissionsUseTeamReassignWizards;
    public boolean PermissionsEditActivatedOrders;
    public boolean PermissionsInstallPackaging;
    public boolean PermissionsPublishPackaging;
    public boolean PermissionsChatterOwnGroups;
    public boolean PermissionsEditOppLineItemUnitPrice;
    public boolean PermissionsCreatePackaging;
    public boolean PermissionsBulkApiHardDelete;
    public boolean PermissionsSolutionImport;
    public boolean PermissionsManageCallCenters;
    public boolean PermissionsManageSynonyms;
    public boolean PermissionsViewContent;
    public boolean PermissionsManageEmailClientConfig;
    public boolean PermissionsEnableNotifications;
    public boolean PermissionsManageDataIntegrations;
    public boolean PermissionsDistributeFromPersWksp;
    public boolean PermissionsViewDataCategories;
    public boolean PermissionsManageDataCategories;
    public boolean PermissionsAuthorApex;
    public boolean PermissionsManageMobile;
    public boolean PermissionsApiEnabled;
    public boolean PermissionsManageCustomReportTypes;
    public boolean PermissionsEditCaseComments;
    public boolean PermissionsTransferAnyCase;
    public boolean PermissionsContentAdministrator;
    public boolean PermissionsCreateWorkspaces;
    public boolean PermissionsManageContentPermissions;
    public boolean PermissionsManageContentProperties;
    public boolean PermissionsManageContentTypes;
    public boolean PermissionsManageExchangeConfig;
    public boolean PermissionsManageAnalyticSnapshots;
    public boolean PermissionsScheduleReports;
    public boolean PermissionsManageBusinessHourHolidays;
    public boolean PermissionsManageDynamicDashboards;
    public boolean PermissionsCustomSidebarOnAllPages;
    public boolean PermissionsManageInteraction;
    public boolean PermissionsViewMyTeamsDashboards;
    public boolean PermissionsModerateChatter;
    public boolean PermissionsResetPasswords;
    public boolean PermissionsFlowUFLRequired;
    public boolean PermissionsCanInsertFeedSystemFields;
    public boolean PermissionsManageKnowledgeImportExport;
    public boolean PermissionsEmailTemplateManagement;
    public boolean PermissionsEmailAdministration;
    public boolean PermissionsManageChatterMessages;
    public boolean PermissionsAllowEmailIC;
    public boolean PermissionsChatterFileLink;
    public boolean PermissionsForceTwoFactor;
    public boolean PermissionsViewEventLogFiles;
    public boolean PermissionsManageNetworks;
    public boolean PermissionsManageAuthProviders;
    public boolean PermissionsRunFlow;
    public boolean PermissionsCreateCustomizeDashboards;
    public boolean PermissionsCreateDashboardFolders;
    public boolean PermissionsViewPublicDashboards;
    public boolean PermissionsManageDashbdsInPubFolders;
    public boolean PermissionsCreateCustomizeReports;
    public boolean PermissionsCreateReportFolders;
    public boolean PermissionsViewPublicReports;
    public boolean PermissionsManageReportsInPubFolders;
    public boolean PermissionsEditMyDashboards;
    public boolean PermissionsEditMyReports;
    public boolean PermissionsViewAllUsers;
    public boolean PermissionsAllowUniversalSearch;
    public boolean PermissionsConnectOrgToEnvironmentHub;
    public boolean PermissionsWorkCalibrationUser;
    public boolean PermissionsCreateCustomizeFilters;
    public boolean PermissionsWorkDotComUserPerm;
    public boolean PermissionsGovernNetworks;
    public boolean PermissionsSalesConsole;
    public boolean PermissionsTwoFactorApi;
    public boolean PermissionsDeleteTopics;
    public boolean PermissionsEditTopics;
    public boolean PermissionsCreateTopics;
    public boolean PermissionsAssignTopics;
    public boolean PermissionsIdentityEnabled;
    public boolean PermissionsIdentityConnect;
    public boolean PermissionsAllowViewKnowledge;
    public boolean PermissionsManageSearchPromotionRules;
    public boolean PermissionsCustomMobileAppsAccess;
    public boolean PermissionsViewHelpLink;
    public boolean PermissionsManageProfilesPermissionsets;
    public boolean PermissionsAssignPermissionSets;
    public boolean PermissionsManageRoles;
    public boolean PermissionsManageIpAddresses;
    public boolean PermissionsManageSharing;
    public boolean PermissionsManageInternalUsers;
    public boolean PermissionsManagePasswordPolicies;
    public boolean PermissionsManageLoginAccessPolicies;
    public boolean PermissionsManageCustomPermissions;
    public boolean PermissionsManageUnlistedGroups;
    public boolean PermissionsModifySecureAgents;
    public boolean PermissionsManageTwoFactor;
    public boolean PermissionsChatterForSharePoint;
    public boolean PermissionsLightningExperienceUser;
    public boolean PermissionsConfigCustomRecs;
    public boolean PermissionsSubmitMacrosAllowed;
    public boolean PermissionsBulkMacrosAllowed;
    public boolean PermissionsShareInternalArticles;
    public boolean PermissionsManageSessionPermissionSets;
    public boolean PermissionsSendAnnouncementEmails;
    public boolean PermissionsChatterEditOwnPost;
    public boolean PermissionsChatterEditOwnRecordPost;
    public boolean PermissionsImportCustomObjects;
    public boolean PermissionsDelegatedTwoFactor;
    public boolean PermissionsChatterComposeUiCodesnippet;
    public boolean PermissionsSelectFilesFromSalesforce;
    public boolean PermissionsModerateNetworkUsers;
    public boolean PermissionsMergeTopics;
    public boolean PermissionsSubscribeToLightningReports;
    public boolean PermissionsManagePvtRptsAndDashbds;
    public boolean PermissionsCampaignInfluence2;
    public boolean PermissionsCanApproveFeedPost;
    public boolean PermissionsAllowViewEditConvertedLeads;
    public boolean PermissionsShowCompanyNameAsUserBadge;
    public boolean PermissionsAccessCMC;
    public boolean PermissionsViewHealthCheck;
    public boolean PermissionsManageHealthCheck;
    public boolean PermissionsViewAllActivities;
    public cls_Description Description;
    public String CreatedDate;  
    public String CreatedById;  
    public String LastModifiedDate; 
    public String LastModifiedById; 
    public String SystemModstamp;   
    public cls_NamespacePrefix NamespacePrefix;
    public String ManageableState;  
    public boolean HasActivationRequired;
    public cls_PermissionSet PermissionSet{get;set;}
    class cls_attributes {
        public String type; 
        public String url;  
    }
      public class cls_PermissionSet {
          Public cls_PermissionSetApplicationVisibility[] ApplicationVisibility;
          Public cls_PermissionSetApexClassAccess[] ApexClassAccess;
          Public cls_PermissionSetCustomPermissions[] CustomPermissions;
          Public cls_PermissionSetExternalDataSourceAccess[] ExternalDataSourceAccess;
          Public cls_PermissionSetFieldPermissions[] FieldPermissions;
          Public cls_PermissionSetObjectPermissions[] ObjectPermissions;
          Public cls_PermissionSetApexPageAccess[] ApexPageAccess;
          Public cls_PermissionSetRecordTypeVisibility[] RecordTypeVisibility;
          Public cls_PermissionSetTabSetting[] TabSetting;
          Public cls_PermissionSetUserPermission[] UserPermission;
          
          
      }
    public class cls_ProfileId {
    }
    public class cls_Description {
    }
   public class cls_NamespacePrefix {
    }
    Public class cls_PermissionSetApplicationVisibility {
        public string application {set;get;}
        public boolean visible {set;get;}
    }
     Public class cls_PermissionSetApexClassAccess {
      public string apexClass {get;set;}
      public boolean Enabled {set;get;}
     }
     Public class cls_PermissionSetCustomPermissions {
         public string name {get;set;}
         public boolean enabled {get;set;}
     }
     Public class cls_PermissionSetExternalDataSourceAccess {
         public boolean Enabled {set;get;}
         public string externalDataSource {set;get;}
     }
     Public class cls_PermissionSetFieldPermissions{
         public boolean editable {set;get;}
         public string field{set;get;}
         public boolean readable{set;get;}
     }
     Public class cls_PermissionSetObjectPermissions{
          public boolean allowCreate {set;get;}
          public boolean allowDelete{set;get;}
          public boolean allowEdit{set;get;}
          public boolean allowRead{set;get;}
          public boolean modifyAllRecords{set;get;}
          public boolean viewAllRecords{set;get;}
         // public string object {set;get;}   
     }
     Public class cls_PermissionSetApexPageAccess{
         public string apexPage{set;get;}
         public boolean enabled{set;get;}
     }
     Public class cls_PermissionSetRecordTypeVisibility{
         public string recordType{set;get;}
         public boolean visible{set;get;}
     }
     Public class cls_PermissionSetTabSetting{
         public string tab{set;get;}
         public string visibility{set;get;}
     }
     Public class cls_PermissionSetUserPermission{
         public string name{set;get;}
         public boolean enabled{set;get;}
     }
    
    
    }